libplacebo-opts=preset=high_quality

# Large backward demuxer cache — keeps decoded data in memory so frame-back-step
# doesn't have to re-seek to a keyframe and decode forward every time
demuxer-max-back-bytes=150MiB

# Native window dragging (zoom-pan is disabled, no conflict)
window-dragging=yes

# Disable the built-in C++ User Interface so mpv is forced to load our custom invisible osc.lua
osc=no

# --- Ultra-Minimal UI Overrides ---
# Vanish the mouse cursor and UI after just 200ms instead of 1000ms
cursor-autohide=200

# Completely disable the floating video title/description text on start or hover
osd-playing-msg=""

# Disable the massive graphical volume bar overlay in the center of the screen
osd-bar=no

# Make the OSD Text (Volume, Speed, pauses) smaller and slightly transparent gray instead of blinding white
osd-font-size=24
osd-color="#AA666666"
osd-border-size=0
osd-on-seek=no

# OSC (Bottom Bar) Layout Overrides:
script-opts=osc-layout=bottombar,osc-windowcontrols=yes,osc-visibility=auto,osc-minmousemove=0,osc-boxalpha=255,osc-fadeduration=1500,osc-hidetimeout=600,osc-scalewindowed=0.5,osc-scalefullscreen=0.5,osc-ghostmode=yes

border=no
